### ISSUE TITLE
mendocino_ridge

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#126]
# AVA: Mendocino Ridge (mendocino_ridge)

name | value
--- | ---
ava_id | mendocino_ridge
cfr_index | 9.158
revision | [T.D. ATF-392, 62 FR 55516, Oct. 27, 1997]
state | CA
county | Mendocino
within | Mendocino\|North Coast
contains | Anderson Valley

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Ornbaun Valley Quadrangle, California, 15 minute series topographic map, 1960; 
2. Navarro Quadrangle, California, 15 minute series topographic map, 1961; 
3. Point Arena Quadrangle, California, 15 minute series topographic map, 1960; 
4. Boonville Quadrangle, California, 15 minute series topographic map, 1959.

## Boundary [src]

(1) Beginning at the Mendocino/Sonoma County line at the mouth of the Gualala River, where the Gualala River empties into the Pacific Ocean, in section 27 of Township 11 North 
(T11N), Range 5 West 
(R5W), located in the southeastern portion of U.S.G.S. 15 minute series map, “Point Arena, California;” 
(2) Then following the Mendocino/Sonoma County line eastward to the southeast corner of section 8 in T11N/R13W, on the U.S.G.S. 15 minute map, “Ornbaun Valley, California;” 
(3) Then from the southeast corner of section 8 in T11N/R13W directly north approximately 3 + miles to the southwest corner of section 9 in T12N/R13W; 
(4) Then proceeding in a straight line in a northwesterly direction to the southwestern corner of section 14 in T13N/R14W; 
(5) Then directly north along the western line of section 14 in T13N/R14W to a point on the western line of section 14 approximately   from the top where the Anderson Valley viticultural area boundary intersects the western line of section 14 in T13N/R14W; 
(6) Then in a straight line, in a northwesterly direction, to the intersection of an unnamed creek and the south section line of section 14, T14N/R15W, on the U.S.G.S. 15 minute series map, “Boonville, California;” 
(7) Then in a westerly direction along the south section lines of sections 14 and 15 in T14N/R15W to the southwest corner of section 15, T14N/R15W, on the U.S.G.S. 15 minute series map, “Navarro, California;” 
(8) Then in a northerly direction along the western section lines of sections 15, 10, and 3 in T14N/R15W in a straight line to the intersection of the Navarro River on the western section line of section 3 in T14N/R15W; 
(9) Then in a northwesterly direction along the Navarro River to the mouth of the river where it meets the Pacific Ocean in section 5 of T15N/R17W; 
(10) Then in a southern direction along the Mendocino County coastline to the Mendocino/Sonoma County line to the beginning point at the mouth of the Gualala River in section 27 of T11N/R15W, on the U.S.G.S. 15 minute series map, “Point Arena, California.”

**Comment by SoominHur** [comment]
Reviewed
- Edit created date in the attribute table

**Comment by MicheleTobias** [comment]
I'm reopening this one because we need to address the instruction before the boundary description:

> Within the boundary description that follows, the viticultural area starts at the 1200 foot elevation (contour line) and encompasses all areas at or above the 1200 foot elevation line. 

I would recommend that we keep the current boundary and add another multipolygon with the polygons that correspond with the areas about 1200 feet.  It will end up looking like squiggly islands.

**Comment by davidkli** [comment]
In progress

**Comment by MicheleTobias** [comment]
I'm just making a note that we need to decide how small is too small for the constituent polygons.  Some of the 1200 foot topo lines form very small circles and these may not be meaningful.  On the other hand, it's the official definition so... this is why we need to think about this as a group.  Ideas and thoughts are welcome!

**Comment by sdelong** [comment]
It would be interesting if you could get the original plot of the region. It must be in a file cabinet somewhere.  

Theoretically, topo lines are a very logical way to define an AVA, especially in terms of the local climate.  However, in practical terms, the exact boundary is not very relevant as it results in lots of little branches that would never work for planting a vineyard. The small circles are even less relevant.  I don't know of any vineyards planted like archipelagos. 

Thinking about the intent of the AVA specification, I would vote for not including the small circles, even if it is the letter of the law.

**Comment by kurtishouser** [comment]
I would opt for including everything above 1200 since it is the official definition. It appears that the Mendocino Wine Growers understand this based on their description of the AVA. https://mendowine.com/ava/mendocino-ridge/

And referring to their map (https://c8ag83oll66pozyz1k8hc1dn-wpengine.netdna-ssl.com/wp-content/uploads/bsk-pdf-manager/2019/08/AVA-Map.pdf) it looks like there are some small areas missing. Quickly scanning the map, below the 're' of Point Arena and two to the right of 
Gualala (you'll need to download the PDF and zoom in to see these). I imagine there are more.

Also, should we be including the encompassing boundary as part of the dataset for this AVA? It's definitely an edge-case but if asking what are the actual boundaries for the Mendocino Ridge AVA then the outer boundary would not be included. The Mendocino Grape Growers map does, sort of (with different colors), but others I've encountered generally don't.
http://www.princeofpinot.com/article/1225/
http://www.everyvine.com/wine-regions/region/Mendocino_Ridge/
https://demystifyingthevine.com/new-world/california/mendocino/

The encompassing boundary is definitely valuable and necessary data and should be maintained somewhere. Maybe a separate file in the same other directory (`/resources/mendocino_ridge_with_encompassing_boundary.geojson`)? Then the user can decide which to use rather than having to go through the error-prone process of directly removing it from the file.

**Comment by sdelong** [comment]
The Mendocino Wine Growers get a map and have their graphic design person use it in their website. I wouldn't try to divine its accuracy.

**Comment by MicheleTobias** [comment]
My gut says include everything, even the small stuff, since people could edit that out.  Right now we have the encompassing boundary and the polygons following the topo lines (minus a few little ones).  I'll probably finish that up soon since I'll need it for a data viz project that's coming up.

I agree that we don't necessarily want to trust or use information from other sources.  It can be helpful to see the maps they produce but it's hard to know what their criteria were for creating any given polygon and it certainly doesn't mean it's the official boundary.

**Comment by MicheleTobias** [comment]
I added in all the little polygons that are probably meaningless in terms of cultivating grapes, but they are officially a part of this AVA.  I removed the big outer boundary that we had and put it into another folder for unofficial boundaries.  This may be the only one that ever goes in there, but at least we have a place to keep it if anyone wants it.
