### ISSUE TITLE
napa_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#140]
# AVA: Napa Valley (napa_valley)

name | value
--- | ---
ava_id | napa_valley
cfr_index | 9.23
revision | 
state | CA
county | Napa
within | North Coast
contains | Atlas Peak\|Calistoga\|Chiles Valley\|Coombsville\|Diamond Mountain District\|Howell Mountain\|Los Carneros\|Mt. Veeder\|Oak Knoll District of Napa Valley\|Oakville\|Rutherford\|Spring Mountain District\|St. Helena\|Stags Leap District\|Wild Horse Valley\|Yountville

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]
(1) “Mt. St. Helena” U.S.G.S. 7.5 minute quadrangle;
(2) “Detert Reservoir” U.S.G.S. 7.5 minute quadrangle;
(3) “St. Helena” U.S.G.S. 15 minute quadrangle;
(4) “Jericho Valley” U.S.G.S. 7.5 minute quadrangle;
(5) “Lake Berryessa” U.S.G.S. 15 minute quadrangle;
(6) “Mt. Vaca” U.S.G.S. 15 minute quadrangle;
(7) “Cordelia” U.S.G.S. 7.5 minute quadrangle;
(8) “Cuttings Wharf” U.S.G.S. 7.5 minute quadrangle; and
(9) Appropriate Napa County tax assessor's maps showing the Napa County-Sonoma County line.

## Boundary [src]
From the beginning point at the conjuction of the Napa County-Sonoma County line and the Napa County-Lake County line, the boundary runs along—
(1) The Napa County-Lake County line;
(2) Putah Creek and the western and southern shores of Lake Berryessa;
(3) The Napa County-Solano County line; and
(4) The Napa County-Sonoma County line to the beginning point.

**Comment by SoominHur** [comment]
Continue Reviewing
- Edit created date in the attribute table
- I also cannot find the petitioner name, so leave it blank in the attribute table
- Add the map year information of the used maps; (1) "Mount St. Helena, (2) Detert Reservoir, (4) Jericho Valley, (7) Cordelia, (8) Cuttings Wharf, because @amberreyes only listed photorevised or photoinspected year. For example, only 1973 was written as the map year information for "Mount St. Helena, CA." But there is no "Mount St. Helena, CA" map made in 1973, instead, there is one made in 1959/photoinspected 1973. So as other maps.
- I could find 15 minute maps of (3) St. Helena, (5) Lake Berryessa, (6) Mt Vaca in the USGS topo view website.
- Maps for (9) Appropriate Napa County tax assessor's maps showing the Napa County-Sonoma County line, I used the same map that @amberreyes used;
(9) "Mark West Springs, CA" 1958, photoinspected 1978, scale 1:24000;
(10) "Calistoga, CA" 1958, photorevised 1980, scale 1:24000;
(11) "Kenwood, CA" 1954, photorevised 1980, scale 1:24000;
(12) "Rutherford, CA" 1951, photorevised 1968, photoinspected 1973, scale 1:24000;
(13) "Sonoma, CA" 1951, photorevised 1980, scale 1:24000;
(14) "Sears Point, CA" 1951, photorevised 1968, scale 1:24000.
- Edit the line following the 'Recreation Area Boundary (Approx)' instead of (2) "the western and southern shores of Lake Berryessa."
