### ISSUE TITLE
north_fork_of_roanoke

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#146]
# AVA: North Fork of Roanoke (north_fork_of_roanoke)

name | value
--- | ---
ava_id | north_fork_of_roanoke
cfr_index | 9.65
revision | [T.D. ATF-129, 48 FR 16250, Apr. 15, 1983, as amended by T.D. ATF-249, 52 FR 5958, Feb. 27, 1987]
state | VA
county | Montgomery|Roanoke
within | 
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. McDonalds Mill Quadrangle, 1965; 
2. Glenvar Quadrangle, 1965; 
3. Elliston Quadrangle, 1965; 
4. Ironto Quadrangle, 1965; 
5. Blacksburg Quadrangle, 1965; and 
6. Newport Quadrangle, 1965.

## Boundary [src]

(1) The point of the beginning is in the north at the intersection of State Routes 785 and 697 in Roanoke County. 
(2) Then the boundary follows State Route 697 northeast over Crawford Ridge to the intersection at State Route 624. 
(3) Then the boundary turns southwest on State Route 624 along the boundary of the Jefferson National Forest and then continues across the Montgomery County line to U.S. 460 
(business). 
(4) Then the boundary follows U.S. Route 460 
(business) south through the town of Blacksburg. 
(5) Then the boundary continues on U.S. Route 460 
(bypass) to the intersection of U.S. Route 460 East, where it turns east for approximately one mile to the intersection of U.S. Interstate Highway 81 at Interchange 37. 
(6) Then the boundary continues northeast on Interstate Highway 81 to its intersection with State Route 603 at interchange 38. 
(7) Then the boundary continues northwest on State Route 603 to its intersection with State Route 629. 
(8) Then the boundary follows State Route 629 
(which later becomes State Route 622 north of Brandshaw Creek) 2 miles across the Roanoke County line to where it intersects the Chesapeake and Potomac Telephone Company right-of-way. 
(9) Then the boundary turns northwest along the C &amp; P right-of-way over Pearis Mountain to the point where the right-of-way intersects State Route 785, one quarter mile northeast of the intersections of State Routes 785 and 697. 
(10) Then the boundary follows State Route 784 back to the beginning point.

**Comment by bsllee** [comment]
Will work on this one, thank you so much!

**Comment by MicheleTobias** [comment]
Hi Brian!
Sorry you're having trouble! I'm on my way back to the states and I'll hopefully have time to dig in and help on Thursday or Friday. Internet here is bad.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MicheleTobias** [comment]
Wow!  That one was a challenge!  I believe that the telephone right away isn't marked explicitly on the map.  It's a gap in the green natural area polygon.  I've marked a purple line next to the line and made an arrow to point it out.  It's the only thing that's about 2 miles from the county line that connects routes 622 and 785.
![capture6](https://user-images.githubusercontent.com/8761459/45238400-8b7f1480-b296-11e8-89fe-64040878d8c7.PNG)

**Comment by MicheleTobias** [comment]
Hi Brian! How's it going with this AVA?  There's no rush.  I just wanted to check in and see if you had any questions.

**Comment by bsllee** [comment]
Hi Dr. Tobias, I hope that your summer was great! I did have a question about the general procedure, and my apologies for not asking earlier and for neglecting this shapefile.

If I wanted to stop halfway through an AVA and finish it later, what should I do in QGIS to make sure that my partially digitized boundaries will snap with each other and form one shapefile? I've been doing the AVAs all at once because I'm not sure how to space out the procedure and I can make more consistent progress. In this case, I couldn't get my two partially digitized boundaries to snap together after Step 8 since I had to stop, so I deleted it. Thanks so much for your help and time!

I moved to Taiwan in the middle of September to begin a Fulbright Grant, but I am almost all settled in and am hoping to start this AVA again on Monday. Thanks again!

**Comment by MicheleTobias** [comment]
Wow! Congrats on the Fullbright Grant!  

When I work on an AVA in parts, here's what I do (there are probably lots of other ways to do it too):
The first round of digitizing is just like you normally do it.  When you come back to add another section, turn on snapping for your AVA file so that you can snap to the vertexes of the previously digitized polygon.  Make sure the polygons collectively fill up the space in the middle of the AVA (no gaps, no overlaps).  After you finish the whole description, you can use the "Merge Selected Features" tool in the Edit Menu to merge all the pieces into one (you have to select them all in the attribute table before it will work).  Before you merge, make sure you commit your changes to your repository.  I've had it erase polygons before and I was really glad to have the back up.

Here's a screenshot of the one I started a while back:
![capture12](https://user-images.githubusercontent.com/8761459/46423953-ad7c8300-c6ec-11e8-9f6b-53ceb591f48d.PNG)

**Comment by MicheleTobias** [comment]
The black line is the boundary between two sections.  The nodes are snapped together so the polygons line up perfectly next to each other.  When you start the new section, just snap the first node of your new polygon to a node on the previous polygon.  Then I digitize the next section of boundary.  When I've done all I want to do at that time, I then make some nodes in what will be the middle of the polygon, and snap to the edge of the other polygons.

Here's a zoomed out view of the one I've been working on.  The squiggly line is the real boundary.  The choppy lines on the other side are the nodes I added to fill out the middle and snap to the first polygon (the little one on the upper right).  This is a big one, so there's more sections to add later.
![capture13](https://user-images.githubusercontent.com/8761459/46425293-1a454c80-c6f0-11e8-86ab-cfdf5fd3bd43.PNG)

**Comment by MicheleTobias** [comment]
Ignore the triangle that's under all of it.

**Comment by bsllee** [comment]
Hi Dr. Tobias,

Thank you again! I finished digitizing this AVA with your help. Unfortunately, I can't access HeinOnline anymore because I'm no longer an employee or student with Davis. My affiliate in Taiwan does not have a subscription. Is it alright if I commit and make the pull request without the attribute data? Thanks, sorry for the trouble!

**Comment by MicheleTobias** [comment]
Yes, that would be fine.  It's no trouble at all.  I can add in the attributes.  Thanks for sticking with this and for all your work on it!

**Comment by MicheleTobias** [comment]
To update this issue: I've merged bsllee's pull request for the polygon.  I will update the attribute table and make any updates needed and close the issue when that is completed.

**Comment by ericallanwest** [comment]
There are two significant revisions needed for this boundary. The 1:100,000 [Radford](https://ngmdb.usgs.gov/ht-bin/tv_browse.pl?id=cd2293ea42c7f93bd049dc318e6bc725) map from 1982 is essential for the telephone right-of-way (9) and the correct route of US 460 Bypass (5). The 1:100,000 map covers the entire boundary and was released the year before the AVA was established. So it is plausible that the petitioner used the single 1:100,000 map to create the boundary description, rather than the six 1:24,000 maps.

**Comment by MicheleTobias** [comment]
Eric, I'm not sure what you're proposing.  Does this completed boundary need to be altered?

**Comment by ericallanwest** [comment]
Yes. I have a revised polygon ready to upload.

**Comment by MicheleTobias** [comment]
Please use the "approved maps" whenever possible.  We only make substitutions when we can't find the maps they describe in the official documents.  The goal is to make the boundary as closely as possible to the described legal boundary.

**Comment by bsllee** [comment]
Sorry for the trouble. Thank you so much for fixing this AVA on my behalf
and bringing it to my attention.

**Comment by MicheleTobias** [comment]
Brian, we spent a lot of time on this one making sure it was right.  I'll be happy to review Eric's suggestions, of course, but the work you did was good and valuable.

**Comment by ericallanwest** [comment]
I was not sure how to suggest an update to a closed issue. I apologize if my tone sounded confrontational. This AVA is literally in our backyard, so we want to ensure that it is as accurate as possible.

US Route 460 Bypass does not exist on the Approved Maps. It is therefore impossible to follow the boundary description without relying on secondary sources. There are compelling reasons to believe that the petitioner used the 1:100,000 Radford map.

GitHub would not let me attach a .geojson file, so it is inside this [north_fork_of_roanoke.zip](https://github.com/UCDavisLibrary/ava/files/3110221/north_fork_of_roanoke.zip) archive.

**Comment by ericallanwest** [comment]
[This GeoTIFF](https://ngmdb.usgs.gov/ht-bin/tv_download.pl?id=cd2293ea42c7f93bd049dc318e6bc725&fmt=tif) is the file I downloaded from topoView to use as a secondary source.

**Comment by bsllee** [comment]
There seems like there's a question about whether I used a single 1:100,000 Radford Map when making this boundary. I used all six of the approved maps, but the 1963 maps for the Glenvar and Elliston Quadrangles because I don't believe there are 1965 versions. Please let me know if I can clarify anything else.

**Comment by MicheleTobias** [comment]
Eric, it's good to have the discussion here.  If you have a new boundary that follows the procedures outlined in our documentation, please submit pull request with the new boundary.

**Comment by alisonsnwong** [comment]
Checked! Edited minor errors in step (6) & step (8)
