### ISSUE TITLE
san_pasqual_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#187]
# AVA: San Pasqual Valley (san_pasqual_valley)

name | value
--- | ---
ava_id | san_pasqual_valley
cfr_index | 9.25
revision | 
state | CA
county | San Diego
within | South Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c

**Comment by SoominHur** [comment]
Reviewed
- Map years of both approved maps and used maps are not indicated. So I used maps with most recent edition year before 1981 (document creation year) except "Escondido, CA." I used the map made in 1996 with edition of 2001. Because according to the description, " the beginning point [starts] at the intersection of Interstate 15 ..." However, the Interstate 15 does not appears on maps created before 1996 (edition of 2001).
Followings are the list of used maps:
(1) “Escondido, CA" 1996, edition of 2001, Scale 1:24000 
(2) “San Pasqual, CA" 1954, photorevised 1971, Scale 1:24000  
(3) “Valley Center, CA" 1968, edition of 1970, Scale 1:24000.
- Relocated the (1) "beginning point at the intersection of Interstate 15 and the 500-foot contour line" because it was on the Interstate 395 (in "Escondido, CA" 1968, ed. 1970) / BR15 (in "Escondido, CA" 1996, ed. 2001).
