### ISSUE TITLE
walla_walla_valley

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#235]
# AVA: Walla Walla Valley (walla_walla_valley)

name | value
--- | ---
ava_id | walla_walla_valley
cfr_index | 9.91
revision | [T.D. ATF-441, 66 FR 11542, Feb. 26, 2001]
state | OR|WA
county | 
within | Columbia Valley
contains | The Rocks District of Milton–Freewater (OR)

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. “Walla Walla,” Washington-Oregon, 1980 
2. “Pendleton,” Oregon-Washington, 1983

## Boundary [src]

(1) The beginning point is on the Walla Walla quadrangle map, in T8N/37E, at the point where the 2,000 foot contour line intersects with an unnamed light duty road approximately 250 feet east of U.S. Highway 12 in Minnick, Washington 
(on maps measured in metric units, this elevation is between the 600 and 650 meter contour lines), 
(2) Then the boundary goes northwest in a straight line for 7 kilometers 
(km), until it intersects with a power line that runs between T8N and T9N, 
(3) Then the boundary follows the power line west for 8 km, where it diverges from the power line and goes west-southwest in a straight line for approximately 33 km to the intersection of 2 unnamed light duty roads in the area marked Ninemile Canyon in the southwest corner of T8N/R33E, 
(4) Then the boundary goes south-southwest in a straight line approximately 8 km, until it reaches U.S. Highway 12, about 2.5 km east of Reese, Washington, 
(5) Then the boundary goes south in a straight line for approximately 8 km, crossing the Washington-Oregon state line and moving onto the Pendleton U.S.G.S. map, where it meets the 450 m contour line in T6N/R32E, near an unnamed peak with an elevation of 461 m, 
(6) Then the boundary follows the 450 m contour line in a generally southeasterly direction until it intersects Dry Creek in T4N/R35E, 
(7) Then the boundary goes southeast along Dry Creek 
(Oregon) until it reaches the 2000 foot contour line, 
(8) Then the boundary follows the 2000 foot contour line in a generally northeasterly direction, crossing the Oregon-Washington state line and returning to the Walla Walla U.S.G.S map, until it reaches the point of beginning.

**Comment by SoominHur** [comment]
In Progress

**Comment by MicheleTobias** [comment]
This AVA is available for someone to work on.

**Comment by dannyo33** [comment]
Currently working on this AVA.

**Comment by dannyo33** [comment]
Steps 7 & 8 specify to follow the 2000 ft contour line, however, this contour line is not present in the approved maps as they are in meters not feet.  #53 Columbia Valley uses 1:250,000 scale maps for Walla Walla and Pendleton to follow the 2000 ft contour line. Since Walla Walla Valley is within Columbia Valley, should I use the 1:250,000 maps specified in the Columbia Valley AVA to trace the 2000 ft contour line for the Walla Walla Valley AVA?

**Comment by dannyo33** [comment]
The specific approved maps are (3) Pendleton, Oregon, Washington, edition of 1954, revised 1973 and (8) Walla Walla, Washington, oregon, edition of 1953, limited revision 1963. Both maps are 1:250,000 in scale but this is not listed in the list of approved maps for Columbia Valley. #53

**Comment by dannyo33** [comment]
The instructions for Columbia Valley #53 follow the same 2000 ft contour line as the one described in the Walla Walla Valley instructions, therefore, I think it would be beneficial to stay consistent and use the 1:250,000 maps described in the Columbia Valley instructions to trace this boundary so that they match exactly. This also makes sense since Walla Walla Valley AVA is within the Columbia Valley AVA. The specific maps are (3) Pendleton, Oregon, Washington, edition of 1954, revised 1973 and (8) Walla Walla, Washington, oregon, edition of 1953, limited revision 1963. Both maps are 1:250,000 in scale.

**Comment by MicheleTobias** [comment]
I think this is a good choice, especially since the Columbia Valley approved maps have worked to define this boundary before.
