### ISSUE TITLE
yountville

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#249]
# AVA: Yountville (yountville)

name | value
--- | ---
ava_id | yountville
cfr_index | 9.160
revision | [T.D. ATF-410, 64 FR 13513, Mar. 19, 1999]
state | CA
county | Napa
within | Napa Valley\|North Coast
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Napa, CA 1951 photorevised 1980; 
2. Rutherford, CA 1951 photorevised 1968; 
3. Sonoma, CA 1951 photorevised 1980; 
4. Yountville, CA 1951 photorevised 1968.

## Boundary [src]

(1) Beginning on the Rutherford quadrangle map at the intersection of the 500 foot contour line with an unnamed stream known locally as Hopper Creek north of the center of Section 3, T6N, R5W, Mount Diablo Meridan 
(MDM); 
(2) Then along the unnamed stream 
(Hopper Creek) southeasterly, and at the fork in Section 3, northeasterly along the stream to the point where the stream intersects with an unnamed dirt road in the northwest corner of Section 2, T6N, R5W, MDM; 
(3) Then in a straight line to the light duty road to the immediate northeast in Section 2, then along the light duty road in a northeasterly direction to the point at which the road turns 90 degrees to the left; 
(4) Then northerly along the light duty road 625 feet, then northeasterly 
(N 40° by 43 ) in a straight line 1,350 feet, along the northern property line of Assessor&#39;s Parcel Number 27-380-08, to State Highway 29, then continuing in a straight line approximately 500 feet to the peak of the 320 plus foot hill along the western edge of the Yountville hills; 
(5) Then east to the second 300 foot contour line, then along said contour line around the Yountville hills to the north to the point at which the 300 foot line exits the Rutherford quadrangle for the second time; 
(6) Then, on the Yountville quadrangle map, in a straight line in a northeasterly direction approximately N34° by 30  E approximately 1,000 feet to the 90 degree bend in the unimproved dirt road shown on the map, then along that road, which coincides with a fence line to the intersection of Conn Creek and Rector Creek; 
(7) Then along Rector Creek to the northeast past Silverado Trail to the Rector Reservoir spillway entrance, then south approximately 100 feet to the 400 foot contour line, then southerly along the 400 foot contour line approximately 4200 feet to the intersection with a gully in section 30, T7N, R4W, MDM; 
(8) Then southwesterly down the center of the gully approximately 800 feet to the medium duty road known as Silverado Trail, then southeasterly along the Silverado Trail approximately 590 feet to the medium duty road known locally Yountville Cross Road; 
(9) Then southwesterly along the Yountville Cross Road 
(denoted as GRANT BDY on the map) approximately 4,700 feet to the main branch of the Napa River, then following the western boundary of the Stags Leap District viticultural area, first southerly down the center of the Napa River approximately 21,000 feet, then leaving the Napa River northeasterly in a straight line approximately 900 feet to the intersection of the Silverado Trail with an intermittent stream at the 60 foot contour line in T6N, R4W, MDM; 
(10) Then along the Silverado Trail southerly approximately 3,200 feet, passing into the Napa quadrangle, to a point which is east of the confluence of Dry Creek with the Napa River; then west approximately 600 feet to said confluence; then northwesterly along Dry Creek approximately 3,500 feet, passing into the Yountville quadrangle to a fork in the creek; then northwesterly along the north fork of Dry Creek approximately 5,700 feet to the easterly end of the light duty road labeled Ragatz Lane; 
(11) Then southwesterly along Ragatz Lane to the west side of State Highway 29, then southerly along Highway 29 by 982 feet to the easterly extension of the north line boundary of Napa County Assessor&#39;s parcel number 034-170-015, then along the north line of APN 034-170-015 and its extension westerly 3,550 feet to the dividing line Between R4W and R5W on the Napa quadrangle, then southwesterly approximately 1000 feet to the peak denoted as 564 
(which is about 5,500 feet easterly of the northwest corner of the Napa quadrangle); then southwesterly approximately 4,000 feet to the peak northeast of the reservoir gauging station denoted as 835; 
(12) Then southwesterly approximately 1,500 feet to the reservoir gauging station, then west to the 400 foot contour line on the west side of Dry Creek, then northwesterly along the 400 foot contour line to the point where the contour intersects the north line of Section 10. T6N, R5W, MDM, immediately adjacent to Dry Creek on the Rutherford, CA map; 
(13) Then northwesterly along Dry Creek approximately 6,500 feet to BM503, then northeasterly approximately 3,000 feet to the peak denoted as 1478, then southeasterly approximately 2,300 feet to the beginning of the creek known locally as Hopper Creek, then southeasterly along Hopper Creek approximately 2,300 feet to the point of beginning.

**Comment by SoominHur** [comment]
Continue Reviewing
- (4) If I "proceed along the light duty road 625 feet, then proceed northeasterly
(N 40°43 E) in a straight line 1,350 feet," it suppose to be along the northern property line of Assessor's Parcel #27-381-008 instead of "along the northern property line of Assessor's Parcel Number 27-380-08." Guess that parcel number must be a typo or has been changed.
- (5) Redraw the line to follow 300' contour because it was following 320' contour line.
- (6) The line was drawn in a straight line in a southeasterly direction approximately 2000' toward the 90 degree bend in the Mill road, so redraw it "in a straight line in a northeasterly direction approximately N34° by 30 E approximately 1,000 feet [toward] the 90 degree bend in the unimproved dirt road." 
- (7) Picked another "gully in section 30, T7N, R4W." Because distance  from 400' contour to Silverado Trail along the center of gully should be (8) "approximately 800 feet." (Also it has to share boundary with 'Stags leap district, CA' since both have same boundary description).
- (9) Moved the node to "intersection of the Silverado Trail with an intermittent stream at the 60 foot contour line in T6N, R4W." Because where node located was the intersection of only Silverado Trail and 60' contour without intermittent stream.
- (11) moved line to go "southerly along Highway 29" because it followed Southern Pacific.
- (12) The line moved to Dry Creek before "the [400'] contour intersects the north line of Section 10. T6N, R5W." So redraw the line along 400' contour line intersects north boundary of Section 10, and then moved to Dry Creek.
