### ISSUE TITLE
clarksburg

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#48]
# AVA: Clarksburg (clarksburg)

name | value
--- | ---
ava_id | clarksburg
cfr_index | 9.95
revision | [T.D. ATF-166, 49 FR 2759, Jan. 23, 1984]
state | CA
county | Yolo
within | 
contains | Merritt Island

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Sacramento West, Calif., 1967 
photorevised 1980.. 
2. Saxon, Calif., 1952 
photorevised 1968.. 
3. Clarksburg, Calif., 1967 
photorevised 1980.. 
4. Florin, Calif., 1968 
photorevised 1980.. 
5. Liberty Island, Calif., 1978. 
6. Courtland, Calif., 1978. 
7. Bruceville, Calif., 1978 
photorevised 1980.. 
8. Isleton, Calif., 1978.

## Boundary [src]

(1) Then southwest in a straight line 1.2 miles along Jefferson Blvd. to the eastern bank of the Sacramento River Deep Water Ship Channel. 
(2) Then southwest along the Sacramento River Deep Water Ship Channel, approximately 17 miles to T5N/R3E, to the Class 5 trail on the levee connecting the Sacramento River Deep Water Ship Channel and the dredger cut Miner Slough, approximately 2 miles from the Solano/Yolo County line. 
(3) Then east along the trail to the Miner Slough. 
(4) Then east along Miner Slough to the point where it joins Sutter Slough, then south along Sutter Slough around the tip of Sutter Island to the junction of Sutter Slough and Steamboat Slough; then north around Sutter Island along Steamboat Slough to Section 8 in T5N/R4E where Steamboat Slough joins the Sacramento River. 
(5) The southeast following the Sacramento River to the point where the Sacramento River meets the Delta Cross Channel at the Southern Pacific Railroad in Section 35, T5N/R4E. 
(6) Then northeast along the Southern Pacific Railroad for 2 miles, to a point   mile past the intersection of the Southern Pacific Railroad and the eastern branch of Snodgrass Slough. 
(7) Then east approximately 2  miles along the levee to Interstate 5 
(under construction). 
(8) Then north approximately 8  miles along Interstate 5 
(under construction, proposed, and completed) to Section 18 in T6N/R5E, at the intersection of Interstate 5 and Hood Franklin Road. 
(9) Then southwest along Hood Franklin Road to the Southern Pacific Railroad Levee, .1 mile northeast of Hood Junction. 
(10) Then north approximately 18 miles along the Southern Pacific Railroad Levee to Section 11 in T7N/R4E, at Freeport Blvd., and then across the Sacramento River at the line between Sections 11 and 14. 
(11) Then northwest along the west bank of the Sacramento River to Burrows Ave. 
(12) Then northwest along Burrows Ave. to the starting point at the intersection of Jefferson Blvd. and Burrows Ave.

**Comment by fyfangyao** [comment]
I am working on this.

**Comment by fyfangyao** [comment]
I use (1) "Saxon, Calif.," 1952 (photorevised 1968) and (2) "Bruceville, Calif.," 1968 (photorevised 1981) because I cannot find the required maps. In addition, I use (1) "Liberty Island, Calif.," 1978 (photorevised 1993),(2) "Courtland, Calif.," 1978 (photorevised 1993) and (3) "Isleton, Calif.," 1978 (photorevised 1993) because approved maps don’t specify the edition years.

**Comment by SoominHur** [comment]
Reviewed.
- Add scale information of the used maps in the attribute table.
- @fyfangyao used  (5) "Liberty Island, CA" 1978, photorevised 1993, scale 1:24000; (6) "Courtland, CA" 1978, photorevised 1993, scale 1:24000; (8) "Isleton, CA" 1978, photorevised 1993, scale 1:24000.. But I used  (5) "Liberty Island, CA" 1978 (1978 ed.), scale 1:24000; (6) "Courtland, CA" 1978 (1978 ed.), scale 1:24000; (8) "Isleton, CA" 1978 (1978 ed.), scale 1:24000 to review, because the document created in 1984, which is before 1993.
- Seems like @fyfangyao confused photorevised year written in the map and edition year listed at the usgs topo view website for "Bruceville, CA" map. So corrected its information like following: (7) "Bruceville, CA" 1968 (1981 ed.), photorevised 1980, scale 1:24000.
- Add description about the beginning point in the attribute table.
- The line went along River Rd levee instead of (10) along the Southern Pacific Railroad Levee, which is at the (9) 0.1 mile northeast of Hood Junction. Thus I edit the line described in (9) & (10).
