### ISSUE TITLE
Check OR Boundaries

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#524]
The following AVAs should be reviewed for this state:

- [x] Columbia Valley
- [x] Willamette Valley
- [x] Rogue Valley
- [x] Umpqua Valley - see issue #501
- [x] Walla Walla Valley
- [x] Applegate Valley
- [x] Columbia Gorge
- [x] Elkton Oregon
- [x] Chehalem Mountains
- [x] Yamhill-Carlton
- [x] Van Duzer Corridor
- [x] Eola-Amity Hills
- [x] McMinnville
- [x] Dundee Hills
- [x] Red Hill Douglas County, Oregon
- [x] The Rocks District of Milton-Freewater
- [x] Ribbon Ridge
- [x] Southern Oregon

Communicate about each AVA's revision status and questions on that AVA's Issue on the Issues Tab (search the closed issues to find all the AVAs).  [Review the Quality Control Procedures](/quality_control_procedure.md) before beginning.  Direct questions to @MicheleTobias.

**Comment by elistockwell** [comment]
Other than border matching above, Columbia Valley is good.

**Comment by elistockwell** [comment]
Was checking willamette valley and noticed that it's border matched to tualatin hills, another Oregon AVA that isn't on this list because it was created after the issue.  Should I add it and other new AVAs to the existing Quality control issues?  Maybe they could have their own issue in case some belong to QC issues that have already closed.

**Comment by MicheleTobias** [comment]
To summarize our Slack discussion, yes,  we need to check the new AVAs that came online recently and each should have their own issue.
