### ISSUE TITLE
cosumnes_river

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#55]
# AVA: Cosumnes River (cosumnes_river)

name | value
--- | ---
ava_id | cosumnes_river
cfr_index | 9.198
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | Sacramento
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Bruceville, Calif., 1968, photorevised 1980; 
2. Florin, Calif., 1968, photorevised 1980; 
3. Elk Grove, Calif., 1968, photorevised 1979; 
4. Galt, Calif., 1968, photorevised 1980; 
5. Lodi North, Calif.,1968, photorevised 1976; and 
6. Thornton, Calif., 1978.

## Boundary [src]

(1) The beginning point is on the Bruceville map at the intersection of the Mokelumne River and Interstate Highway 5, T5N, R5E. From the beginning point, proceed north 8.5 miles along Interstate 5 to its intersection with an unnamed light duty road, locally known to the west of Franklin as Hood-Franklin Road, section 18, T6N, R5E 
(Florin Quadrangle); then 
(2) Proceed east 1.2 miles straight on Hood-Franklin Road to its intersection with Franklin Boulevard in the village of Franklin, section 17, T6N, R5E 
(Florin Quadrangle); then 
(3) Proceed north 4.3 miles on Franklin Boulevard to its intersection with Sims Road on the west and Sheldon Road to the east at the northwest corner of section 28, T7N, R5E 
(Florin Quadrangle); then 
(4) Proceed east 2.4 miles on Sheldon Road to its intersection with State Route 99 at the northern boundary section 26, T7N, R5E 
(Florin Quadrangle); then 
(5) Proceed south-southeast 6 miles on State Route 99, crossing over the Elk Grove map, to the road&#39;s intersection with the Southern Pacific railway line at McConnell, section 20, T6N, R6E 
(Galt Quadrangle); then 
(6) Proceed south-southeast 8.7 miles along the Southern Pacific railway line to its intersection with Kost Road, section 34, T5N, R6E 
(Lodi North Quadrangle); then 
(7) Proceed west and then north 3.8 miles on Kost Road to its intersection with New Hope Road, T5N, R6E 
(Lodi North Quadrangle); then 
(8) Proceed west then south 2.8 miles on New Hope Road to its intersection with the Mokelumne River and the Sacramento-San Joaquin County line, T5N, R5E 
(Thornton Quadrangle); and 
(9) Proceed northerly then westerly 
(downstream) for about 2.7 miles along the meandering Mokelumne River, returning to the beginning point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Bruceville Quad, Cali., 7.5 minute series, 1968, revised 1981,“ “Elk Grove, Cali., 7.5 minute series, 1968, revised 1980,” “Lodi North, Cali., 7.5 minute series, 1968, revised 1977,” and “Thornton, Cali., 7.5 minute series, 1978, revised 1985.”

**Comment by SoominHur** [comment]
Reviewed
- Add scale information of the used maps.
- Seems like @fyfangyao confused the photorevised year written on the map and edition year appears at the usgs topoview site. Therefore, rewrite the photorevised years written on the maps as "photorevised 19xx" and edition years appear at the usgs topoview site as "(19XX ed.)". Following are the rewritten information of used maps; (1) "Bruceville, CA" 1968 (1981 ed.), photorevised 1980, Scale 1:24000; (2) "Florin, CA" 1968, photorevised 1980, Scale 1:24000; (3) "Elk Grove, CA" 1968 (1980 ed.), photorevised 1979, Scale 1:24000; (4) "Galt, CA" 1968, photorevised 1980, Scale 1:24000; (5) "Lodi North, CA"1968 (1977 ed.), photorevised 1976, Scale 1:24000; and (6) "Thornton, CA" 1978 (1985 ed.), Scale 1:24000.
- (3) describes to put a node at the intersection of Franklin Boulevard with "Sims Road on the west and Sheldon Road to the east at the northwest corner of section 28" (T7N, R5E, Florin Quadrangle). Franklin Blvd actually intersects with Sims Rd at the northwest corner of section 28 (T7N, R5E). However, Sheldon Rd stops before it actually intersects with Franklin Blvd. Instead, there is an unnamed road that goes south then west from Sheldon Rd and intersects with Franklin Blvd in Section 29. I guess @fyfangyao  put a node described in (3) at the intersection between this unnamed road and Franklin Blvd because she assumed this unnamed road as Sheldon Rd. Searched on Google Maps, but the road is disappeared currently. Therefore, moved the node described in (3) to the intersection between Franklin Blvd and Sims Rd at the northwest corner of Section 28.
