### ISSUE TITLE
Outer Coastal Plain History

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#552]
This AVA has the following revisions:
- [ ] [T.D. TTB-58, 72 FR 6167, Feb. 9, 2007]

- [ ] [T.D. TTB-58, 72 FR 6167, Feb. 9, 2007, as amended by T.D. TTB-148, 82 FR 57659, Dec. 7, 2017]

Each revision should be represented by a polygon inside the .geojson file for this AVA.  See the [Adding Historical Boundaries](https://github.com/UCDavisLibrary/ava/blob/master/digitizing_ava_boundaries.md#adding-historical-ava-boundaries) document for more information on how to add historical boundaries.

**Comment by MicheleTobias** [comment]
@davidkli I'm making an issue for trying out the history instructions on this AVA that you determined needed a different boundary to meet our current time point specifications.  I'm also using this as a trial for how the issues should look.  Feedback on any part of the process is welcome!

**Comment by kurtishouser** [comment]
I would recommend keeping each historical boundary in a separate file and placing it in a different folder. This will provide more flexibility and allow the users to decide how they want to incorporate the historical boundaries into their project.

I'm a web developer and with the current proposal if I just want the current boundaries I would have to either manually remove the others from the file first (error prone) or write additional code to extract just the current data (also error prone). And for boundaries with multiple revisions the chronological order with in the `features` array would have to be maintained across the entire dataset for consistency (and best practice).

I would also recommend keeping the `ava_id` the same across all files rather than appending the valid start date to the end. Use this format for the file names instead.

**Comment by davidkli** [comment]
As for now, I have added the historical boundary polygon to the AVA. I am not entirely sure about the accuracy of some fields in the attribute table, particularly the valid_start and valid_end fields.

**Comment by MicheleTobias** [comment]
Thanks @davidkli ! I'll take a look at the attribute table carefully.  This will help me also clarify what should be in these columns and where the directions can be more clear.  Teamwork!

**Comment by MicheleTobias** [comment]
@kurtishouser I'm thinking about the concerns you have. The way the data structure for this project was originally planned, we have the individual files for containing information about each AVA so it makes more sense to me to keep one file for each AVA that contains all the boundaries for that AVA.  This would maintain consistency when we combine all the AVAs into one file - so each line in the combined vector file has a unique ID.  I do plan to create a product with just the current boundaries.  Would that help your situation?

**Comment by kurtishouser** [comment]
@MicheleTobias
Thanks for asking.

I still think one file for each boundary, current and historical, is a more flexible approach. I'm importing the GeoJSON data into a backend database and it makes more sense to have one boundary per record with my use case. It's also much easier to import if there's only one boundary in each file.

I wasn't really concerned about the `ava_id` since I usually let the database system assign the unique id automatically. But your approach is definitely the better choice in the context of an app like QGIS. I may have to reconsider mine... :)

I also noticed that there doesn't appear to be any chronological order with the features array. With Outer Coastal Plain the current boundary is the first element but with Yakima Valley it's the last one. I would suggest a consistent order so code can retrieve the current boundary directly rather than having to locate it based on some other field property.

Thanks again for including me in the process. Cheers!

**Comment by MicheleTobias** [comment]
The major goal of this project is to support research. We provide data and expect that the folks who use it will be able to manipulated it to meet their specific needs.  I would suggest sorting on one of the date fields if you need them in a specific order. We are currently working to fix inconsistencies in the formatting and fix some of the date issues that have arisen out of confusion about having multiple CFR documents, so using the date fields should get easier in the next month or two.
