### ISSUE TITLE
New interactive TTB AVA Map?

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#555]
Certainly not an issue but I discovered this yesterday and thought I'd share. Is this new? It's quite nice! There are downloadable Shapefiles as well.
https://www.ttb.gov/images/AVA/

**Comment by MicheleTobias** [comment]
That site and dataset came out a little while ago... I think last summer.  Their methods are not as well documented as ours (at least when I last explored it) and I wasn't able to get a hold of someone to ask for clarification about their methods. It seems the TTB outsourced it to a consultant, which seemed silly because when this happened, we were already almost done with the boundaries.

**Comment by ericallanwest** [comment]
Here are more details:

https://www.blueraster.com/mapping-americas-wine-regions/
https://storymaps.arcgis.com/stories/dd22ddbe5a0c433a80e2a75b61065570

These links go to great lengths to explain how Blue Raster (the contractor) used historical topographic maps for reference. But it appears that the polygons were constructed using modern GIS datasets, quite unlike the UC Davis approach.

In my opinion, this is a very efficient way to tackle the problem. While the resulting polygons are not historically/temporally accurate, they do reflect a common-sense interpretation of the AVA boundaries.

**Comment by MicheleTobias** [comment]
Thanks! It's good to know the TTB have documentation for their methods now. Yes, they are different than the ones we use in this project.  The applications and uses will be different.
