### ISSUE TITLE
Create list of historic boundaries to update

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#591]
I've got the code for this on my local computer. I need to make sure it's up to date, run it, and also put it in the GitHub repo for future reference.

**Comment by MicheleTobias** [comment]
@erklopez I think you were working on updating the `ScrapeRevisionHistories.R` file. Is that correct?

**Comment by erklopez** [comment]
Yes

**Comment by MicheleTobias** [comment]
What's the status of that script? I know we put it on hold for the documentation overhaul, but let's add some details here so we know where it's at and where the trouble spots are.

**Comment by erklopez** [comment]
Some changes were made to the website while I put the script on hold. I will look at the changes and try to change the script to work with them. Also, there are other approaches that I would like to try to use, like looking at the API and getting the json instead of the HTML.

**Comment by kurtishouser** [comment]
I have a NodeJS script that does this. It uses the [CFR](https://www.govinfo.gov/bulkdata/CFR) XML file (updated annually) and the [ECFR](https://www.govinfo.gov/bulkdata/ECFR/title-27) XML file (updated throughout the year) from the [Bulk Data Repository](https://www.govinfo.gov/bulkdata). However, it looks like the new ECFR site provides an API endpoint directly to the [Subpart C](https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C) [XML](https://www.ecfr.gov/api/versioner/v1/full/2022-05-03/title-27.xml?part=9) file which is fantastic! This is probably the best option now instead of an HTML page.

If you find a JSON version of this file definitely post it here. Parsing XML files is rather cumbersome.

**Comment by erklopez** [comment]
https://www.ecfr.gov/developers/documentation/api/v1#/

**Comment by erklopez** [comment]
The CFR XML file can be called through the API, but the JSON files returned only contain the hierarchy, I am currently building a script that builds a data frame from the latest date and compares it to our current version CITA string.

**Comment by kurtishouser** [comment]
FYI: The structure of the eCFR XML file has changed a bit. They are now including links to the amendment documents before the effective date of the updated/new AVAs. See https://www.ecfr.gov/compare/2022-06-03/to/2022-06-02/title-27/chapter-I/subchapter-A/part-9. Look for the green highlighting at Clear Lake and on the bottom of the page. Here's the actual XML document, https://www.ecfr.gov/api/versioner/v1/full/2022-06-03/title-27.xml?part=9&subpart=C.

This produces some odd text for new AVAs (`§ 9.284 xxx`). I don't know if it will affect your R script but it broke my NodeJS script. Because the new *and* updated AVAs have this `<XREF>` node I had to use a different criteria to filter out the useless stuff at the bottom. Just something to be aware of...

**Comment by erklopez** [comment]
The current script is now outputting a data frame with the section name, section, revision_string_current(referring to the one on the eCFR website), and cfr_revision_history(referring to our revision string on the ava project).

The output of the ScrapeRevisionHistories_new.R is a csv file on the avas_aggregated_files with the avas that require updating on this project.

**Comment by erklopez** [comment]
The output is now part of the reports directory and contains two separate data frames, one with the avas that require updating (need_updating_avas) and one with new updates that have not been included yet (new_avas). Avas assigned to have different revision strings by typos or ecfr missing avas are no longer included in the final output, but instead can be seen by manually running the script and inspecting 'nonmatching' data frame.

**Comment by kurtishouser** [comment]
Fair Play has already been updated and shouldn't be listed in the report.

It appears that the code is using `valid_start` to determine which polygon is the most recent.
`z<-which.max(x$valid_start)`

For the most recent revision of this AVA the value is `null` so maybe this is the reason it's incorrectly listed. The `null' value will need to be corrected.

Maybe use `ava_id` instead. It's probably less like to be missing a value.

**Comment by MicheleTobias** [comment]
This script is for our internal process, so I'm less concerned about false positives because we'll sort those out. @erklopez it might be helpful to understand where these are coming from, but I'm mainly interested in being able to generate issues for the revisions that need to get digitized.

**Comment by erklopez** [comment]
Refer to #841 for more details. Currently working on fixing the output of the new avas to look for the correct ones and not rely on the order of avas created and the number difference between eCFR and ours. Future steps also include the atomized creation of issues for new and updated avas.
