### ISSUE TITLE
Napa Valley History

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#593]
This AVA has the following revisions:

- [ ] [T.D. ATF-79, 46 FR 9063, Jan. 28, 1981]
- [ ] [T.D. ATF-201, 50 FR 12533, Mar. 29, 1985]

Each revision should be represented by a polygon inside the .geojson file for this AVA.  See the [Adding Historical Boundaries](https://github.com/UCDavisLibrary/ava/blob/master/digitizing_ava_boundaries.md#adding-historical-ava-boundaries) document for more information on how to add historical boundaries.

**Comment by kurtishouser** [comment]
It appears that ATF-201 only removed `(not mandatory before January 1, 1983)` from the heading `§ 9.23 Napa Valley (not mandatory before January 1, 1983)` so there is probably no reason to add an additional feature to the file since there would be no change to the current data. If so, then this issue could be closed.

Document: https://www.govinfo.gov/content/pkg/FR-1985-03-29/pdf/FR-1985-03-29.pdf

**Comment by MicheleTobias** [comment]
We probably won't add any additional boundaries if the revisions don't make substantial changes to the boundary or the attributes (like the name).
