### ISSUE TITLE
Sonoma Valley History

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#596]
This AVA has the following revisions:

- [ ] [T.D. ATF-96, 46 FR 59238, Dec. 4, 1981]
- [ ] [T.D. ATF-201, 50 FR 12533, Mar. 29, 1985]
- [ ] [T.D. ATF-249, 52 FR 5956, Feb. 27, 1987]

Each revision should be represented by a polygon inside the .geojson file for this AVA.  See the [Adding Historical Boundaries](https://github.com/UCDavisLibrary/ava/blob/master/digitizing_ava_boundaries.md#adding-historical-ava-boundaries) document for more information on how to add historical boundaries.

**Comment by kurtishouser** [comment]
It appears that ATF-201 only removed `(not mandatory before January 1, 1983)` from the heading `§ 9.29 Sonoma Valley (not mandatory before January 1, 1983)` so there is probably no reason to add an additional feature to the file for this revision since there would be no change to the ATF-96 data. See #593.

Document: https://www.govinfo.gov/content/pkg/FR-1985-03-29/pdf/FR-1985-03-29.pdf

**Comment by elistockwell** [comment]
Working on this.

**Comment by MicheleTobias** [comment]
All these things seem pretty minor. Let's just make sure we have the attributes correct and call it good for now.

**Comment by elistockwell** [comment]
Attributes look up to date with most recent revision.
