### ISSUE TITLE
Fix Clockwise AVAs

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#700]
For geojson polygons, the direction following the border of an "exterior ring" (as opposed to a "hole") is counterclockwise.  Some of the AVAs are clockwise, and should be fixed.  So far the only one I've found is Alexander Valley.  One easy way to check is to add two vertices right next to each other and drag them in opposite different directions far from the AVA, take note of the changed coordinates, then look for them in the geojson file.  We will probably want to write a script to find and fix these.

**Comment by MicheleTobias** [comment]
We can also script looking for the direction of these boundaries. The sf package has a [tool to check and enforce the right direction](https://r-spatial.github.io/lwgeom/reference/st_force_polygon_cw.html).
For reference, there is a [specification for polygons in geojson](https://tools.ietf.org/html/rfc7946#section-3.1.6)

**Comment by kurtishouser** [comment]
The right-hand rule is part of the RFC 7946 (GeoJSON 2016) spec. By default the GDAL GeoJSON driver used by QGIS exports GeoJSON 2008 (deprecated) files.
https://gdal.org/drivers/vector/geojson.html
https://gdal.org/drivers/vector/geojson.html#rfc-7946-write-support

To write RFC 7946 files try adding the following to the Custom Options -> Layer box at the bottom when exporting the layer.
```
RFC7946=YES
COORDINATE_PRECISION=15
```
I tested this with Alisos Canyon (because it has only 9 coordinate pairs) and it did reverse them. I also checked it at https://geojsonlint.com and it passed. The original file did not. So perhaps this is the solution going forward.

Note: This will remove the `"crs": {...}` block as well since it is no longer part of the RFC 7946 spec.

**Comment by MicheleTobias** [comment]
Thanks, Kurtis! This is good to know. We'll probably write an R script to find and fix the ones we haven't dealt with, but going forward, it's helpful to know we can fix the issue with the specs in QGIS.

**Comment by kurtishouser** [comment]
Perhaps exporting the layer and including the arguments should be part of the documentation for future AVAs. Then there would be no need to fix anything with a script.

**Comment by MicheleTobias** [comment]
I think we'll need the script in the future because the legal definitions of the AVA boundaries go clockwise but GeoJSON wants them counter clockwise.  @elistockwell wrote the script and I applied it yesterday. I should have closed this issue but I forgot (lots going on in DataLab lately).

**Comment by kurtishouser** [comment]
@MicheleTobias As a final step, if everybody would export the layer as GeoJSON and add the above arguments to the Custom Options -> Layer box then the resulting file will be correct. In addition to the winding I've also discovered that this process performs other valuable updates such as removing unnecessary escaping, fixing dates and checking that the `MultiPolygon` designation is correct.

The R script becomes unnecessary.

**Comment by MicheleTobias** [comment]
@elistockwell can you try this with the next AVA you complete?
