### ISSUE TITLE
west_sonoma_coast

### ISSUE THREAD

**Issue by elistockwell** [UCDavisLibrary/ava#834]
New AVA to digitize!

https://www.ecfr.gov/current/title-27/chapter-I/subchapter-A/part-9/subpart-C/section-9.283

Digitizing Methods:
https://ucdavislibrary.github.io/ava/methods.html#digitize-new-boundaries

**Comment by MicheleTobias** [comment]
West Sonoma Coast might be the  new name for San Luis Obispo. Read the Federal Register Final Rule document for West Sonoma Coast to find out. If it *is* a re-name, we'll need to handle it in our "history" protocol instead.

**Comment by alisonsnwong** [comment]
The McGuire Ridge (2015) topo map was used instead of the 2012 map as there were no township sections.

The West Sonoma Coast AVA shares partial boundaries with the Sonoma Coast & Fort Ross-Seaview AVA. Border matching were done using the snapping tool for simple boundaries & the dissolve tool for more detailed boundaries.
