### ISSUE TITLE
false positives & missing item in avas_aggregated_files/need_updating_avas.csv

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#841]
`Cape May Peninsula` and `Champlain Valley of New York` are false positives.
I don't know what the project process is but it's probably best to visually inspect the script's output and remove the false positives before merging the file into the repo. Or maybe just create git issues for each AVA after running the script and don't add anything to the repo. It's one less file to manage. 

`Santa Lucia Highlands` is not on the list but an update is available.

I don't know R but I skimmed the code and found it quite self explanatory. I noticed a few things.
- It appears that the code is comparing the eCFR to the contents of the `avas_aggregated_files/avas.geojson`. This file was last updated in the `master` branch 3 months ago so the script is potentially working with data that is out of sync. My script reads from all of the individual files in the `avas` folder so I know I have the latest data in the `master` branch. It's cumbersome, but as an alternative maybe you can use the code that generates this file and create the data structure in memory first. Otherwise it's best to run the aggregation script first.
- Line 99 `for (i in 1:261)` I'm guessing  this mirrors the number of AVAs currently in the dataset. If so, is it possible to make it dynamic instead of having to update it every time  a new AVA file is added?
- Maybe this is an R data-frame constraint, but I would avoid altering the revision history data before comparing them. You'll encounter more false positives but sometimes this is helpful. If I remember correctly, I've had to correct some with extra spaces, usually at the end. If they are removed first then we'll never see the error.
- It also looks like there's code to flag new AVAs. Are there any plans to output this as well?

**Comment by MicheleTobias** [comment]
Thanks, @kurtishouser for this feedback.
@erklopez I can update the aggregated files, but reading in all of the individual files would be a way around the aggregated files not being updated.  For Line 99, you could get the dimensions of the dataframe (or the number of files in the folder) so the number doesn't have to be updated by hand.

**Comment by kurtishouser** [comment]
@MicheleTobias @erklopez
It looks like line 33 has a hard-coded value in it as well that will need to be changed.
`subpartC<-subpartC[2:262,] #getting rid of general section 9.21`

Can you incorporate some of the existing code in `mergeGeoJson.R` instead of having to write something new to read each file?
Lines 60-61:
```
current.avas<-allsf[which(is.na(allsf$valid_end)),]
write_sf(current.avas, dsn="avas.geojson", driver="GeoJSON", delete_dsn=TRUE)
```
Just before writing the file it looks like `current.avas` has the required data for the new script.

**Comment by erklopez** [comment]
I've found that the ava aggregated file has a different cfr_revision_history than its individual files. When I check whether the file has the correct string the aggregated file returns TRUE, but the individual file will return FALSE. I have checked that the data I am getting is the same as the one on the geojson files and indeed the aggregated ava and individual files contain different strings. I am not sure why this happens, could it be that someone else working on the project has been updating the ava aggregated file instead of the individual ones? I cannot come up with another answer for the difference. I would expect the aggregated file to be behind updating but instead appears to be ahead.

**Comment by kurtishouser** [comment]
@erklopez Are you using the correct `cfr_revision_history` from the individual files? When there are amendments to the AVA the individual files have multiple features, and therefore multiple `cfr_revision_history` values. Because the feature array isn't in any kind of order, for my script I opted to sort each feature by the `ava_id` property and then selected the first feature to get the latest value.
`['arroyo_seco', 'arroyo_seco19830516', 'arroyo_seco20060717']`

@MicheleTobias Nearly all `ava_id` values have the incorrect format seen above (no underscore preceding the date).

**Comment by MicheleTobias** [comment]
@erklopez make sure you're updating your branch. But also, it could be that your code is failing because of the historic polygons. As Kurtis mentioned, if a boundary has been revised, there are multiple polygons, so there are multiple revision history strings for those boundaries. Let me know if you want to talk more about this.

@kurtishouser thanks for the heads up about the `ava_id` column. That's an oversight that needs to be fixed. I think I know when that happened but it needs fixing regardless. I'll make an issue for it. We're training up a new student to work on this project, so we'll have more hands to help out soon.
