### ISSUE TITLE
AVA IDs for Older Revisions

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#843]
The format of the `ava_id` column should be `name_date` where the date is in YYYYMMDD format, however, it appears that many of our IDs for historic revisions are missing the underscore.

For example, Arroyo Seco has the following IDs: arroyo_seco, arroyo_seco1983051, and arroyo_seco20060717, but they should be arroyo_seco, arroyo_seco_1983051, and arroyo_seco_20060717.

We can fix this by hand (editing each of the AVA boundary files), or we can do it in R using regex to find and fix the incorrectly formatting records.

**Comment by kurtishouser** [comment]
This will probably be an unpopular suggestion but perhaps the valid start date should be appended to all `ava_id` values.

Reasoning:
- It's impossible to correctly sort the QGIS attribute table by the `ava_id` column.
- Within the context of a database it's generally a very bad idea to change the ID.
- Also considering a database, it's more likely that a user will query by the AVA name instead of the id: "Give me 'Napa Valley' where `valid_end` is null" rather than "Give me 'Napa Valley' where `ava_id` doesn't have eight digits at the end"

Just a thought.
