### ISSUE TITLE
The latest merge script alters the geometry data in the aggregated files

### ISSUE THREAD

**Issue by kurtishouser** [UCDavisLibrary/ava#906]
I was looking at the latest aggregated files and noticed that the geometry data has been modified. In most cases it's just reduced precision to 7 digits. The rest are changes to the last 6+ digits. The geometry type has been changed from `Polygon` to `MultiPolygon` as well.

I did some more checking and noticed several files with reduced precision in the `/avas` folder as well. It appears that the `st_make_valid()` R function is causing this (now present in the merge script).

Also see commits:
https://github.com/UCDavisLibrary/ava/commit/10e4ca1f13c4141dfec8f0c9065bb97088f2f30b
https://github.com/UCDavisLibrary/ava/commit/c1d308f9c6d4a693d6cb62abd25c216968938ba8

Maybe it's best to use the tools available with QGIS to check/fix geometries and avoid doing it with R scripts. The geometry should be checked and fixed before any pull requests are merged into master anyway. Use the R script to merge, order and check for invalid geometries, but just report errors.

Recovering the lost precision of the files in the `/avas` folder would be tedious (if desired for consistency). Perhaps now would be a good time to export to the RFC 7946 spec. Fifteen decimals places is unnecessary and has a significant impact on the file size.
https://datatracker.ietf.org/doc/html/rfc7946#section-11.2

**Comment by MicheleTobias** [comment]
Thanks for finding this. I'll do some digging into the `st_make_valid()` function. I don't know why it would reduce the precision, but it's totally possible that's what's happening.

With a project of this size, we need to be able to use scripts, so R will remain a part of our workflow.  QGIS has different definitions of polygon validity. The polygons that threw errors in our R aggregation script were valid in QGIS.

**Comment by MicheleTobias** [comment]
I did some digging. I think it's actually `read_sf()` that's causing the problem. Any AVA I read in individually is coming in to R with way fewer digits than we have in the repo. I haven't figured out if it's just truncating for display purposes or if it's really not there. It might also be caused at the write step.

**Comment by MicheleTobias** [comment]
I'm pretty sure this is the result of a change in the `sf` package. I'll get in touch with some folks who might know more about the change and see what we can do to fix this.

**Comment by MicheleTobias** [comment]
Never mind. It's `st_make_valid()` that's doing it.  R was truncating the display of coordinates making it look like they came in shorter than they did.

**Comment by MicheleTobias** [comment]
What a puzzle to solve! Good news! We can easily get around this. It turns out we just need to set the precision of the AVA files before we make them valid. Something like this (where `ava` is the ava boundary):

`ava<-st_set_precision(ava, 15)` 

Then run `st_make_valid()` on `ava`

@alisonsnwong can you implement that?

**Comment by alisonsnwong** [comment]
Yeah sure! To make sure, would I add that to every R script that has the `st_make_valid()` line?

**Comment by kurtishouser** [comment]
@MicheleTobias The main issue with this approach is that the merge script is potentially altering downstream data in `/avas_aggregated_files` and not addressing the original error in the upstream data  in `/avas/*.geojson`. The merge script shouldn't change any data. It's fine to check for invalid geometry but just report it. The correction needs to be done in the source GeoJSON file.

It's also treating `st_make_valid()` as a black box. Data goes in. Data comes out. What invalid geometries is it looking for? Did it alter the data? If so, why? What was wrong? How was it fixed?

As far as I can tell QGIS does not correct invalid geometry unless instructed to do so. There are the **Check validity** and **Fix geometries** tools but they don't seem to cover all possibilities. The better option in QGIS is the **[Geometry Checker](https://docs.qgis.org/3.28/en/docs/user_manual/plugins/core_plugins/plugins_geometry_checker.html)** plugin. I had to enable it in **Plugins -> Manage and Install Plugins...** so that would appear as **Check Geometries...** in the **Vector** menu.

Even with this plugin manual correction will be required in some instances, especially for self intersection errors.

Take a look at the southeast corner of Cienaga Valley. I don't know if this was corrected manually or automatically with some other tool/R script but I'd be skeptical that it's supposed to look like a titled hourglass. It doesn't look like this on the TTB map.

**Comment by MicheleTobias** [comment]
R and the sf package are open source, so you can know what it's doing. Reading the github repos for both the st_make_valid() function from sf and the geos makevalid which it is based on, the tool in our case just removes duplicate points. If there was a self-intersection, it would re-order the points to avoid that. Handling processes with several hundred boundaries by hand isn't practical, so we need to rely on tools from programming languages like R. The packages we use are developed by people we trust because they are pillars in the field. Occasionally, a tool has a behavior that we don't anticipate, such as what happened with st_make_valid(), but when we discover it, we fix it. 

Looking back at the history for Ciengega Valley, I believe this was a case of the TTB's description being a little wacky. See #362 and #47. I personally addressed this one by hand.  I'll add a an issue to have one of my students check it again, but I think it's just one of those oddballs. Since we follow the TTB's description at closely as possible, some of the boundaries are a little odd. The TTB uses a different set of methods and may be correcting boundary descriptions more than we do.

**Comment by MicheleTobias** [comment]
I believe we solved theses issues with #908. I will rerun the aggregation scripts.

**Comment by kurtishouser** [comment]
@MicheleTobias I believe the updated merge script is still missing an important step. I will await the new aggregated files, check them and report back if this is the case. If it doesn't encounter any invalid geometries I won't know for sure though...

The Geometry Checker is a useful plugin to have in the toolbox. I wasn't suggesting it be used instead of any of your automated processes, but as a compliment for anybody that wants to contribute and doesn't, nor wants to, use R. I think this project should encourage its use a final step before submitting any PRs. I will be using it myself.

I wasn't being critical of the sf package either, just concerned with how it's being used here.
