### ISSUE TITLE
Replace Web Map Tiles

### ISSUE THREAD

**Issue by MicheleTobias** [UCDavisLibrary/ava#933]
Replace the tiles (basemap) on the [Explore the Data web map](https://ucdavislibrary.github.io/ava/explore.html). Stamen no longer hosts the data we were using. It has been [relocated to Stadia](https://maps.stamen.com/stadia-partnership/). We can use these or find a different base map.

**Comment by erklopez** [comment]
Stadia now requires us to sign it, while that is an option since our usage would not require payment, and no credit card is required, it uses an API, which would require us to append the API key to the title layer url. It would be best to talk about alternatives before making the API key available through the html [Explore the Data web map](https://ucdavislibrary.github.io/ava/explore.html)

**Comment by MicheleTobias** [comment]
I had to do the same fix for the Traveling GIS Chat Book map. I think using OSM tiles for this is a good solution. The map is super low traffic and it doesn't require anyone to maintain an account somewhere: https://github.com/MicheleTobias/traveling-gis-chat-book

**Comment by kurtishouser** [comment]
Leaflet is now at version 1.9.4 if you want to update it.

Is the `leaflet-geojson-vt` plugin is being used anywhere in the code?
 
Also, the first visualization is looking for a JS map file that doesn't exist. See browser console. Probably minor.
`https://ucdavislibrary.github.io/ava/visualizations/crosstalk.min.js.map`.
