### ISSUE TITLE
jahant

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ava#96]
# AVA: Jahant (jahant)

name | value
--- | ---
ava_id | jahant
cfr_index | 9.199
revision | [T.D. TTB-50, 71 FR 40414, July 17, 2006]
state | CA
county | Sacramento|San Joaquin
within | Lodi
contains | 

[src]: https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=371db32ecca6629af6dccad2a39d7833&mc=true&n=sp27.1.9.c
## Approved Maps [src]

1. Lodi North, Calif., 1968, photorevised 1976; 
2. Thornton, Calif., 1978; 
3. Galt, Calif., 1968, photorevised 1980; 
4. Lockeford, Calif., 1968, photorevised 1979; and 
5. Clay, Calif., 1968, photorevised 1980, minor revision 1993.

## Boundary [src]

(1) The beginning point is on the Lodi North map at the intersection of Peltier Road and the Mokelumne River, section 16 south boundary line, T4N, R6E. From the beginning point, proceed westerly 
(downstream) 6.7 miles along the Mokelumne River to its intersection with New Hope Road, about 0.7 mile north of the village of Thornton, T5N, R5E 
(Thornton Quadrangle); then 
(2) Proceed north then east for 3 miles on New Hope Road to its intersection with Kost Road, T5N, R6E 
(Lodi North Quadrangle); then 
(3) Proceed south then east for 4.1 miles on Kost Road to its intersection with Lincoln Way, section 35, T5N, R6E 
(Lodi North Quadrangle); then 
(4) Proceed southeast 0.15 mile on Lincoln Way to its intersection with Dry Creek, section 35, T5N, R6E 
(Lodi North Quadrangle); then 
(5) Proceed easterly 
(upstream) 7 miles along Dry Creek, crossing twice over and back at the southeast corner of the Galt map, and then crossing over the northwest corner of the Lockeford map, to Dry Creek&#39;s intersection with Elliott Road, section 26, T5N, R7E 
(Clay Quadrangle); then 
(6) Proceed south 4.5 miles on Elliott Road to its intersection with Peltier Road at the southeast corner of section 14, T4N, R7E 
(Lockeford Quadrangle); and 
(7) Proceed west 8.3 miles on Peltier Road, returning to the beginning point.

**Comment by fyfangyao** [comment]
I am working on it.

**Comment by fyfangyao** [comment]
I use “Lodi North, Quad, Cali., 7.5 minute series, 1968, photorevised 1977,“ “Thornton, Cali., 7.5 minute series, 1978, photorevised 1985,” “Clay, Cali., 7.5 minute series, 1968, photorevised 1980, minor revision 1993,” “Lockeford, Cali., 7.5 minute series, 1968, photorevised 1980.”

**Comment by SoominHur** [comment]
Reviewed
- Removed the nodes along the Mokelumne River pass by the (1) intersection with New Hope Road, about 0.7 mile north of the village of Thornton, T5N, R5E.
- Corrected lines that occasionally follow along Sacramento/San Joaquin County Boundary instead of (5) along Dry Creek .
- Add scale information of used maps in the attribute table.
- Could find the maps listed in the Approved Maps and use them for reviewing/editing; (1) "Lodi North, CA" 1968, photorevised 1976 (1977 ed.), Scale 1:24000; (2) "Thornton, CA" 1978, Scale 1:24000; (3) "Galt, CA" 1968, photorevised 1980, Scale 1:24000; (4) "Lockeford, CA" 1968, photorevised 1979 (1980 ed.), Scale 1:240000; and (5) "Clay, CA" 1968, photorevised 1980, minor revision 1993, Scale 1:24000.
